# ===========================================================================
# Held-out validation for MAPSO / EM / SGD.
#
# Idea: the dataset is trajectories generated by a Bayesian (belief-state
# POMDP-optimal) agent -- NOT by the FSC being fit. Split it once into
# train/val *before* fitting anything, fit all three methods on train only,
# then score each method's learned (rho, pi, g) on val. This is the direct
# test for your central result: a method can drive train NLL to ~0 (e.g.
# MAPSO's degenerate softmax-saturation cases) while generalizing badly --
# that only shows up on held-out data.
#
# Framework-agnostic: takes plain numpy (rho, pi, g) probability arrays, so
# it works the same whether they came from MAPSO, train_em, or the torch
# train_sgd (which already returns numpy after unpack_theta_probs).
# ===========================================================================
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D


# ---------------------------------------------------------------------------
# Split
# ---------------------------------------------------------------------------

def split_dataset(dataset, val_frac=0.2, seed=None):
    """One split, reused for all three methods so the comparison is
    apples-to-apples. Fit MAPSO/EM/SGD on `train` only; never touch `val`
    until scoring.

    Note: this takes val_frac OUT of `dataset`, so len(train) < len(dataset).
    If you need len(train) to equal a specific target (e.g. you want
    n_data trajectories actually used for training, with validation data
    on top of that rather than carved out of it), generate more episodes
    up front and use split_dataset_n instead -- see its docstring."""
    rng = np.random.default_rng(seed)
    n = len(dataset)
    idx = rng.permutation(n)
    n_val = max(1, int(round(n * val_frac)))
    val_idx, train_idx = idx[:n_val], idx[n_val:]
    train = [dataset[i] for i in train_idx]
    val = [dataset[i] for i in val_idx]
    return train, val


def split_dataset_n(dataset, n_train, seed=None):
    """Like split_dataset, but you specify the exact TRAIN size instead of
    a validation fraction taken out of the whole. Use this when you want
    the training set to equal a specific n_data regardless of how much
    validation data you also want -- generate `n_data + n_val` episodes
    up front, then call this with n_train=n_data:

        n_data = 10
        n_val = 5
        dataset_raw = generate_dataset(pomdp, fsc, n_episodes=n_data + n_val, ...)
        dataset_encoded = encode_dataset(dataset_raw)
        train_set, val_set = split_dataset_n(dataset_encoded, n_train=n_data, seed=2)
        assert len(train_set) == n_data

    Raises if dataset is smaller than n_train -- that means you didn't
    generate enough episodes to cover both train and val.
    """
    rng = np.random.default_rng(seed)
    n = len(dataset)
    if n_train > n:
        raise ValueError(
            f"n_train={n_train} exceeds dataset size={n}. Generate at least "
            f"n_train + (desired val size) episodes before splitting."
        )
    idx = rng.permutation(n)
    train_idx = idx[:n_train]
    val_idx = idx[n_train:]
    train = [dataset[i] for i in train_idx]
    val = [dataset[i] for i in val_idx]
    return train, val


# ---------------------------------------------------------------------------
# Likelihood (numpy, log-space forward algorithm -- same model as the
# torch training code, just re-derived here for standalone scoring so this
# file doesn't depend on which method produced rho/pi/g)
# ---------------------------------------------------------------------------

def _logsumexp(x, axis=None):
    m = np.max(x, axis=axis, keepdims=True)
    m = np.where(np.isfinite(m), m, 0.0)  # guard all -inf rows
    s = np.sum(np.exp(x - m), axis=axis, keepdims=True)
    out = m + np.log(s)
    return np.squeeze(out, axis=axis) if axis is not None else out.reshape(())


def sequence_nll(actions, obs, rho, pi, g, eps=1e-12):
    """NLL of one (actions, obs) trajectory under fixed FSC params.
    eps floors probabilities before log() -- this is what keeps a
    saturated (near-0/1) MAPSO solution from producing -inf/NaN on val
    data it didn't see, instead of silently blowing up."""
    log_rho = np.log(np.maximum(rho, eps))
    log_pi = np.log(np.maximum(pi, eps))
    log_g = np.log(np.maximum(g, eps))

    T = len(actions)
    a0 = actions[0]
    log_alpha = log_rho + log_pi[a0]   # log_pi has shape (A, M); log_pi[a] -> (M,)

    for t in range(T - 1):
        a_t, y_t, a_next = actions[t], obs[t], actions[t + 1]
        log_g_slice = log_g[:, :, a_t, y_t]                 # (mp, m)
        log_alpha = _logsumexp(log_g_slice + log_alpha[None, :], axis=1)
        log_alpha = log_alpha + log_pi[a_next]

    ll = _logsumexp(log_alpha, axis=None)
    return -float(ll)


def dataset_nll(dataset, rho, pi, g, per_timestep=True, eps=1e-12):
    """Mean NLL over a dataset. per_timestep=True normalizes by total
    timesteps (comparable across train/val splits of different size);
    per_timestep=False gives mean per-trajectory NLL."""
    total_nll = 0.0
    total_T = 0
    for actions, obs in dataset:
        total_nll += sequence_nll(actions, obs, rho, pi, g, eps=eps)
        total_T += len(actions)
    return total_nll / total_T if per_timestep else total_nll / len(dataset)


# ---------------------------------------------------------------------------
# Cross-method evaluation
# ---------------------------------------------------------------------------

def evaluate_methods(fitted_params, train_set, val_set, per_timestep=True, eps=1e-12):
    """
    fitted_params : dict, e.g. {"MAPSO": (rho, pi, g), "EM": (rho, pi, g), "SGD": (rho, pi, g)}
        Each (rho, pi, g) must have been fit on `train_set` only.

    Returns dict: {method: {"train_nll": ..., "val_nll": ..., "gap": val - train}}
    """
    out = {}
    for name, (rho, pi, g) in fitted_params.items():
        train_nll = dataset_nll(train_set, rho, pi, g, per_timestep=per_timestep, eps=eps)
        val_nll = dataset_nll(val_set, rho, pi, g, per_timestep=per_timestep, eps=eps)
        out[name] = {"train_nll": train_nll, "val_nll": val_nll, "gap": val_nll - train_nll}
    return out


def evaluate_methods_all_trials(fitted_params_all_trials, train_set, val_set,
                                 per_timestep=True, eps=1e-12):
    """
    Like evaluate_methods, but scores EVERY trial's fitted params instead of
    collapsing each method down to its single best run. A bar chart of just
    the best run hides how consistently (or not) a method overfits -- e.g.
    MAPSO might have a handful of degenerate softmax-saturation restarts
    with ~0 train NLL and terrible val NLL, and a few well-behaved ones,
    but "best-of" only ever shows you the well-behaved one. This keeps the
    full spread so you can scatter train_nll vs val_nll per trial and see
    the cloud, not just one point per method.

    fitted_params_all_trials : dict, e.g.
        {"MAPSO": [(rho, pi, g), (rho, pi, g), ...],   # one tuple per trial/restart
         "EM":    [(rho, pi, g), ...],
         "SGD":   [(rho, pi, g), ...]}
        Every (rho, pi, g) in every list must have been fit on `train_set`
        only (trials differ by random init/restart, not by data).

    Returns dict: {method: {"train_nll": [...], "val_nll": [...], "gap": [...]}}
        -- one entry per trial, in the same order as the input list. Lists
        are already index-aligned (train_nll[i], val_nll[i] are the same
        trial), so you can zip() or np.array() straight into a scatter.
    """
    out = {}
    for name, trials in fitted_params_all_trials.items():
        train_nlls, val_nlls, gaps = [], [], []
        for (rho, pi, g) in trials:
            train_nll = dataset_nll(train_set, rho, pi, g, per_timestep=per_timestep, eps=eps)
            val_nll = dataset_nll(val_set, rho, pi, g, per_timestep=per_timestep, eps=eps)
            train_nlls.append(train_nll)
            val_nlls.append(val_nll)
            gaps.append(val_nll - train_nll)
        out[name] = {"train_nll": train_nlls, "val_nll": val_nlls, "gap": gaps}
    return out


def flatten_for_scatter(trial_metrics):
    """Convenience reshape of evaluate_methods_all_trials()'s output into flat
    parallel arrays, ready for e.g. plt.scatter(train_nll, val_nll, c=...):

        methods, train_nll, val_nll, gap = flatten_for_scatter(trial_metrics)

    `methods` is a string array of the same length as the others, so you can
    use it directly to color/group points by method (e.g. one scatter() call
    per np.unique(methods), or pass it through a colormap lookup)."""
    methods, train_nll, val_nll, gap = [], [], [], []
    for name, m in trial_metrics.items():
        n = len(m["train_nll"])
        methods.extend([name] * n)
        train_nll.extend(m["train_nll"])
        val_nll.extend(m["val_nll"])
        gap.extend(m["gap"])
    return (np.array(methods), np.array(train_nll, dtype=float),
            np.array(val_nll, dtype=float), np.array(gap, dtype=float))


def _nll_jitter_panel(ax, name_to_vals, methods, colors, title, ylabel="NLL",
                       seed=0, label_pad=0.2, percentile=95):
    """Draws one jittered-scatter/median/min panel -- the same visual
    language as the MAPSO/EM/SGD-across-restarts plot -- onto `ax`, for
    whatever per-trial NLL values you pass in (e.g. train_nll or val_nll
    from evaluate_methods_all_trials). Unlike that original plot, the
    values here are already raw dataset_nll output, not an optimizer's
    internal tracked/regularized loss -- so there's no separate
    raw_by_name reload step; vals.min() IS the number to label.
    """
    rng = np.random.default_rng(seed)
    all_vals = np.concatenate([np.asarray(name_to_vals[m]) for m in methods])
    ylim_bottom = -label_pad
    ylim_top = np.percentile(all_vals, percentile)
    ylim_top = max(0.5, ylim_top + 0.1 * ylim_top)

    for i, name in enumerate(methods):
        vals = np.asarray(name_to_vals[name])
        x = np.full(len(vals), i) + rng.normal(0, 0.05, len(vals))
        ax.scatter(x, vals, s=45, color=colors[name], alpha=0.8,
                   edgecolor="black", linewidth=0.3, zorder=3)
        best = np.argmin(vals)
        ax.scatter(i, vals[best], marker="*", s=220, color=colors[name],
                   edgecolor="black", linewidth=1, zorder=5)
        ax.text(i, -0.07, f"{max(vals.min(), 0):.1e}", ha="center", va="top",
                fontsize=9, color=colors[name], fontweight="bold")
        median_val = np.median(vals)
        ax.hlines(median_val, i - 0.18, i + 0.18, linewidth=2, color=colors[name])
        ax.axhline(vals.min(), color=colors[name], linestyle="--", linewidth=1, alpha=0.6)
        n_clipped = int(np.sum(vals > ylim_top))
        if n_clipped > 0:
            ax.annotate(f"+{n_clipped} above view", xy=(i - 0.7, median_val + 0.02),
                        fontsize=7.5, color=colors[name], style="italic",
                        va="center", ha="left")

    legend_elements = [
        Line2D([0], [0], marker="*", linestyle="None", color="dimgray",
               markerfacecolor="dimgray", markeredgecolor="black",
               markersize=14, label="Minimum NLL"),
        Line2D([0], [0], color="dimgray", linewidth=2, label="Median NLL"),
    ]
    ax.legend(handles=legend_elements, frameon=True, loc="upper left")
    ax.set_ylim(ylim_bottom, ylim_top)
    ax.set_xticks(range(len(methods)))
    ax.set_xticklabels(methods)
    for tick, name in zip(ax.get_xticklabels(), methods):
        tick.set_color(colors[name])
        tick.set_fontweight("bold")
    ax.set_ylabel(ylabel)
    ax.set_title(title)


def plot_train_val_trials(trial_metrics, methods=None, colors=None,
                           mc=None, n_data=None, seed=0):
    """3-panel figure, matching the restarts-jitter visual style:
    left = train NLL per trial, middle = held-out val NLL per trial,
    right = train-vs-val scatter per trial (the dashed diagonal is
    val == train; points above/left of it are the normal generalization
    direction, points below/right -- low train NLL but high val NLL --
    are the overfitting signature).

    trial_metrics : output of evaluate_methods_all_trials()
    colors : dict {method: color}. Defaults to matplotlib's color cycle
        if not given -- pass your own MAPSO/EM/SGD colors dict to match
        the rest of your figures.
    mc, n_data : optional, folded into the panel titles if given.
    """
    methods = methods or list(trial_metrics.keys())
    colors = colors or {m: c for m, c in zip(
        methods, plt.rcParams["axes.prop_cycle"].by_key()["color"])}

    train_by_name = {m: np.array(trial_metrics[m]["train_nll"]) for m in methods}
    val_by_name = {m: np.array(trial_metrics[m]["val_nll"]) for m in methods}

    title_suffix = ""
    if mc is not None or n_data is not None:
        title_suffix = f" (mc={mc}, n_data={n_data})"

    fig, axes = plt.subplots(1, 3, figsize=(19, 5), dpi=150)

    _nll_jitter_panel(axes[0], train_by_name, methods, colors,
                       title=f"Train NLL Across Restarts{title_suffix}",
                       ylabel="Train NLL", seed=seed)
    _nll_jitter_panel(axes[1], val_by_name, methods, colors,
                       title=f"Held-out Val NLL Across Restarts{title_suffix}",
                       ylabel="Val NLL", seed=seed)

    ax = axes[2]
    for name in methods:
        ax.scatter(train_by_name[name], val_by_name[name], s=45,
                   color=colors[name], alpha=0.8, edgecolor="black",
                   linewidth=0.3, label=name, zorder=3)
    lo = min(min(train_by_name[m].min() for m in methods),
             min(val_by_name[m].min() for m in methods))
    hi = max(max(train_by_name[m].max() for m in methods),
             max(val_by_name[m].max() for m in methods))
    ax.plot([lo, hi], [lo, hi], color="dimgray", linestyle="--", linewidth=1,
            zorder=1, label="val = train")
    ax.set_xlabel("Train NLL")
    ax.set_ylabel("Val NLL")
    ax.set_title(f"Train vs. Held-out NLL per Trial{title_suffix}")
    ax.legend(frameon=True, loc="best")

    fig.tight_layout()
    return fig, axes


# ---------------------------------------------------------------------------
# Plots
# ---------------------------------------------------------------------------




def plot_convergence_with_val(nll_histories, time_or_epoch_axes, val_nlls,
                               title="Training convergence vs. held-out NLL",
                               xlabel="Epoch", ylabel="NLL", save_path=None):
    """
    nll_histories : dict {method: nll_history list} (already recorded during
        training, e.g. from train_sgd's returned nll_history)
    time_or_epoch_axes : dict {method: x-axis values}, e.g. range(len(hist))
        or the returned time_history
    val_nlls : dict {method: scalar val NLL} -- drawn as a horizontal
        reference line per method, in the same color as its training curve

    Shows each method's training curve descending toward its floor, with a
    dashed horizontal line at its held-out NLL -- a curve that plunges far
    below its own val line is overfitting, not converging.
    """
    fig, ax = plt.subplots(figsize=(8, 5))
    colors = plt.rcParams["axes.prop_cycle"].by_key()["color"]
    for i, method in enumerate(nll_histories):
        color = colors[i % len(colors)]
        ax.plot(time_or_epoch_axes[method], nll_histories[method],
                label=f"{method} (train)", color=color)
        ax.axhline(val_nlls[method], color=color, linestyle="--", alpha=0.7,
                    label=f"{method} (val)")
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.legend()
    ax.grid(alpha=0.3)
    fig.tight_layout()
    if save_path:
        fig.savefig(save_path, dpi=150, bbox_inches="tight")
    return fig

def diagnose_split_bias(train_set, val_set, rho_true, pi_true, g_true,
                         per_timestep=True, eps=1e-12, n_bootstrap=200, seed=0):
    """
    Sanity check for the 'val NLL < train NLL' observation.

    Scores the *true* generative parameters (not anything fitted) on both
    splits. If the gap shows up here too, it's just sampling variance from
    the train/val split -- not a bug in the fitting pipeline. If it doesn't
    show up here but does show up for fitted params, the fitting code is
    leaking val information somewhere (early stopping / restart selection
    / warm-start touching val_set).
    """
    train_nll = dataset_nll(train_set, rho_true, pi_true, g_true,
                             per_timestep=per_timestep, eps=eps)
    val_nll = dataset_nll(val_set, rho_true, pi_true, g_true,
                           per_timestep=per_timestep, eps=eps)
    gap = val_nll - train_nll

    print(f"True-params train NLL: {train_nll:.6f}")
    print(f"True-params val NLL:   {val_nll:.6f}")
    print(f"Gap (val - train):     {gap:+.6f}  "
          f"{'(val LOWER than train -- consistent with pure split variance)' if gap < 0 else '(val higher, as textbook-expected)'}")

    # Bootstrap: resample val-sized chunks from train to see how big a gap
    # this magnitude is under pure sampling noise, given your actual val size.
    rng = np.random.default_rng(seed)
    n_val = len(val_set)
    boot_gaps = []
    for _ in range(n_bootstrap):
        idx = rng.choice(len(train_set), size=n_val, replace=False) \
              if n_val <= len(train_set) else rng.choice(len(train_set), size=n_val, replace=True)
        resample = [train_set[i] for i in idx]
        resample_nll = dataset_nll(resample, rho_true, pi_true, g_true,
                                    per_timestep=per_timestep, eps=eps)
        boot_gaps.append(resample_nll - train_nll)
    boot_gaps = np.array(boot_gaps)

    print(f"\nBootstrap (n={n_bootstrap}, resampling {n_val}-sized chunks from train):")
    print(f"  mean gap: {boot_gaps.mean():+.6f}, std: {boot_gaps.std():.6f}")
    print(f"  observed gap {gap:+.6f} sits at the "
          f"{(boot_gaps < gap).mean()*100:.1f}th percentile of the bootstrap distribution")

    return {"train_nll": train_nll, "val_nll": val_nll, "gap": gap,
            "boot_gaps": boot_gaps}

import numpy as np
from val import dataset_nll, split_dataset

def multi_split_bias_check(dataset, rho_true, pi_true, g_true,
                            val_frac=0.2, n_splits=200,
                            per_timestep=True, eps=1e-12, seed=0):
    """
    Test 1: is 'val < train under true params' a PERSISTENT bias, or just
    noise from one particular split?

    Re-splits the SAME dataset many times with fresh random seeds and
    scores the true params (never fitted, so no leakage possible) on each
    split. If the gap is centered near zero and roughly symmetric, what
    you saw before was sampling noise. If it's reliably negative across
    splits, something about the split/scoring methodology itself is
    biased (not a fitting-code leak, since true params never touch fit).
    """
    rng = np.random.default_rng(seed)
    gaps = []
    for i in range(n_splits):
        split_seed = int(rng.integers(0, 2**31 - 1))
        train_set, val_set = split_dataset(dataset, val_frac=val_frac, seed=split_seed)
        train_nll = dataset_nll(train_set, rho_true, pi_true, g_true,
                                 per_timestep=per_timestep, eps=eps)
        val_nll = dataset_nll(val_set, rho_true, pi_true, g_true,
                               per_timestep=per_timestep, eps=eps)
        gaps.append(val_nll - train_nll)
    gaps = np.array(gaps)

    frac_negative = (gaps < 0).mean()
    print(f"True-params val-train gap across {n_splits} fresh splits:")
    print(f"  mean: {gaps.mean():+.6e}, std: {gaps.std():.6e}")
    print(f"  fraction of splits with val < train: {frac_negative:.1%}")
    print(f"  (should be ~50% if it's pure noise; far from 50% = real bias "
          f"in split.py/val.py itself)")
    return gaps


def fresh_holdout_check(generate_dataset_fn, encode_dataset_fn, pomdp, fsc_true,
                         fitted_params, n_fresh=500, per_timestep=True, eps=1e-12, seed=123):
    """
    Test 2: is the OFFICIAL val_set specifically contaminated (leaked into
    fitting somewhere), or does ANY held-out data behave this way?

    Generates a brand-new dataset from the true agent that fitted_params
    (MAPSO/EM/SGD results) could not possibly have touched -- not even
    indirectly via early stopping, restart selection, or warm-start
    embedding. Score each method's fitted params on it.

    If this "clean" holdout shows the normal direction (val >= train) while
    your official val_set still shows val < train for the same fitted
    params, that confirms the official val_set is leaking into fitting
    somewhere upstream (check restart-selection / early-stopping /
    warm-start code for any place a variable named val_set, or the full
    `dataset`, gets referenced instead of train_set).

    generate_dataset_fn / encode_dataset_fn: your existing dataset
    generation + encoding functions (same ones used to build the original
    dataset), passed in so this file doesn't need to import your sim code.
    """
    fresh_raw = generate_dataset_fn(pomdp, fsc_true, n_episodes=n_fresh, seed=seed)
    fresh_set = encode_dataset_fn(fresh_raw)

    print(f"Scoring fitted params on a FRESH {n_fresh}-episode holdout "
          f"(never seen by any fitting code):")
    for name, (rho, pi, g) in fitted_params.items():
        fresh_nll = dataset_nll(fresh_set, rho, pi, g, per_timestep=per_timestep, eps=eps)
        print(f"  {name}: fresh-holdout NLL = {fresh_nll:.3e}")
    print("\nCompare these to each method's official train_nll/val_nll. "
          "If fresh-holdout NLL >= train_nll (normal direction) but the "
          "official val_nll < train_nll, the official val_set is leaking "
          "into fitting somewhere.")
    return fresh_set